### ISSUE TITLE
Non paired-end reads

### ISSUE THREAD

**Issue by abayega** [Mkchouk/MiRCA#3]
Hi,

can I use Illumina reads that are not paired-end as the input in the first step?

Thanks

**Comment by Mkchouk** [comment]
Hello,
I used Spades assembler to create contigs.
If Spades handles non paired-read reads then MiRCA can handle non paired end reads.
you can use the recent version of Spades 3.9.
if you have any for MiRCA you can visit this links:
[MiRCA_dexa](https://www.researchgate.net/publication/312486908_Efficient_Hybrid_De_Novo_Error_Correction_and_Assembly_for_Long_Reads)
[MiRCA_Bibm](https://www.researchgate.net/publication/312571513_Hybrid_error_correction_approach_and_de_novo_assembly_for_minion_sequencing_long_reads)
Thanks

**Comment by abayega** [comment]
Hi, one other issue; the compilation of main.c gives the following warnings;

$ cd /home/abayega/software/MiRCA-master && gcc main.c
main.c: In function ‘print_ligne’:
main.c:49:13: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
      printf("   lenght qseq=       %d\t",strlen(r.qseq));
             ^
main.c:50:14: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
       printf("   lenght Sseq= %d",strlen(r.sseq));
              ^
main.c: In function ‘table_optimiser’:
main.c:196:20: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
             printf("len chaine: %d\n",strlen(chaine3));
                    ^
The executable a.out is created. Is there any correction to be done in the main.c file before compiling?
Thanks

**Comment by abayega** [comment]
Ooh, I am running on Ubuntu;
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by Mkchouk** [comment]
It works??

**Comment by abayega** [comment]
No. Only prints OKOKOK on screen.
Have you released v1.2 coz the one I download says v1.1 in the readme.txt.

On  executing;
gcc main_trim.c
main_trim.c: In function 'sequence_replace':
main_trim.c:91:4: error: 'res' undeclared (first use in this function)
    res=start+lenght;
    ^
main_trim.c:91:4: note: each undeclared identifier is reported only once for each function it appears in

I think you still have an issue to resolve.

**Comment by Mkchouk** [comment]
just a parameter not declared.
but for me, i executed the program and it works!!!
download the last version of MiRCA.
Thanks

**Comment by abayega** [comment]
Also with gcc  version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

gcc main_trim.c
main_trim.c: In function ‘print_ligne’:
main_trim.c:46:13: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
      printf("   lenght qseq=       %d\t",strlen(r.qseq));
             ^
main_trim.c:47:14: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
       printf("   lenght Sseq= %d",strlen(r.sseq));
              ^
main_trim.c: In function ‘sequence_replace’:
main_trim.c:91:4: error: ‘res’ undeclared (first use in this function)
    res=start+lenght;
    ^
main_trim.c:91:4: note: each undeclared identifier is reported only once for each function it appears in
main_trim.c: In function ‘table_optimiser’:
main_trim.c:201:20: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
             printf("len chaine: %d\n",strlen(chaine3));
                    ^

**Comment by Mkchouk** [comment]
change the type of "%d"!!
and download the last version of MiRCA in github.
i compile with gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) and it works!!!

**Comment by Erin-Vaughn** [comment]
I'm having the same issue, it won't compile under gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

I'm not well-versed enough in C to edit the source code. Have you released a fix to this yet? I'm only seeing v1.1

**Comment by Erin-Vaughn** [comment]
I was able to compile the script on another computing system but it now fails due to segfault.
